/* eslint-disable @next/next/no-html-link-for-pages */
import { chatGPTSignInPath } from "../chatgpt-auth";

type MarketingPage = "home" | "features" | "pricing" | "security" | "contact" | "privacy" | "terms";

const plans = [
  { name: "Starter", price: "$49", description: "For one operator building a repeatable outreach motion.", features: ["250 submitted calls monthly", "2 concurrent calls · 1 seat", "1,000 prospects · 3 campaigns", "3 integrations · 30-day audit history"], best: false },
  { name: "Growth", price: "$149", description: "For teams turning qualified conversations into a dependable pipeline.", features: ["2,000 submitted calls monthly", "10 concurrent calls · 5 seats", "5,000 prospects · 20 campaigns", "10 integrations · 180-day audit history"], best: true },
  { name: "Pro", price: "$399", description: "For established outbound teams operating at meaningful volume.", features: ["10,000 submitted calls monthly", "20 concurrent calls · 20 seats", "25,000 prospects · 100 campaigns", "50 integrations · 365-day audit history"], best: false },
];

export default function MarketingSite({ page = "home", signedIn = false }: { page?: MarketingPage; signedIn?: boolean }) {
  const appPath = signedIn ? "/app" : chatGPTSignInPath("/app");
  return <main className="marketing-shell">
    <header className="marketing-header"><a className="marketing-brand" href="/"><span className="marketing-mark"><i /><i /></span><span>APPOINTMENT SETTER<small>AI calling control room</small></span></a><nav aria-label="Public navigation"><a href="/features">Features</a><a href="/pricing">Pricing</a><a href="/security">Security</a><a href="/contact">Contact</a></nav><div className="marketing-actions"><a className="button button-secondary" href={appPath}>{signedIn ? "Open app" : "Log in"}</a>{!signedIn ? <a className="button button-primary" href={chatGPTSignInPath("/app")}>Sign up free</a> : null}</div></header>
    {page === "home" ? <HomeContent appPath={appPath} /> : page === "features" ? <FeaturesContent appPath={appPath} /> : page === "pricing" ? <PricingContent appPath={appPath} /> : page === "security" ? <SecurityContent /> : page === "contact" ? <ContactContent /> : page === "privacy" ? <LegalContent title="Privacy policy" kind="privacy" /> : <LegalContent title="Terms of service" kind="terms" />}
    <footer className="marketing-footer"><div><strong>AI Appointment Setter</strong><p>Consent-first outbound calling and calendar scheduling for responsible teams.</p></div><div><a href="/features">Features</a><a href="/pricing">Pricing</a><a href="/security">Security</a></div><div><a href="/contact">Contact</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><div><a href={appPath}>{signedIn ? "Open workspace" : "Log in"}</a><a href={chatGPTSignInPath("/app")}>Create account</a></div></footer>
  </main>;
}

function HomeContent({ appPath }: { appPath: string }) { return <>
  <section className="marketing-hero"><div><span className="eyebrow">AI OUTREACH, WITH GUARDRAILS</span><h1>Qualified conversations, booked automatically.</h1><p>Launch consented AI calling campaigns, qualify real interest, and place confirmed appointments directly on your team’s calendar.</p><div className="hero-actions"><a className="button button-primary" href={appPath}>Start your 14-day trial</a><a className="text-link" href="/features">See how it works →</a></div><div className="trust-row"><span>Clear AI disclosure</span><span>Role-based access</span><span>Permanent outreach history</span></div></div><div className="hero-console" aria-label="Campaign control preview"><span className="console-label">LIVE CAMPAIGN CONTROL</span><div className="console-head"><div><small>Qualified demo outreach</small><strong>Protected queue active</strong></div><span className="status-pill">Ready</span></div><div className="console-metrics"><span><small>Eligible</small><strong>842</strong></span><span><small>Live calls</small><strong>8 / 10</strong></span><span><small>Booked</small><strong>31</strong></span></div><div className="console-flow"><i /><span>Consent verified</span><i /><span>AI disclosed</span><i /><span>Meeting confirmed</span></div></div></section>
  <section className="marketing-proof"><span>OUTLOOK</span><span>GOOGLE CALENDAR</span><span>TWILIO VOICE</span><span>OPENAI</span><span>TEAM WORKSPACES</span></section>
  <section className="marketing-section"><div className="section-intro"><span className="eyebrow">ONE CONTROL ROOM</span><h2>Everything between a prospect list and a confirmed meeting.</h2><p>The platform combines campaign setup, provider limits, compliant call execution, scheduling, team permissions, and a complete activity ledger.</p></div><div className="feature-grid"><Feature n="01" title="Protected campaign launches" text="Every prospect is rechecked for consent, DNC evidence, local calling hours, and account limits before dialing."/><Feature n="02" title="Human-quality AI conversations" text="Campaign-specific agents qualify interest using your factual product brief and supported objectives."/><Feature n="03" title="Confirmed calendar booking" text="The agent checks availability and creates an appointment only after the prospect confirms an exact time and email."/></div></section>
  <section className="marketing-cta"><span className="eyebrow">READY WHEN YOU ARE</span><h2>Make every call accountable.</h2><p>Start with 10 trial calls. Connect your own providers when you are ready to launch.</p><a className="button button-primary" href={appPath}>Create your workspace</a></section>
  <section className="marketing-disclaimer">Operators remain responsible for consent, DNC, recording, caller-ID, and jurisdiction-specific telemarketing requirements. The agent identifies itself as AI.</section>
  </>; }

function FeaturesContent({ appPath }: { appPath: string }) { return <PageFrame eyebrow="PRODUCT" title="Built for accountable appointment setting." intro="From spreadsheet import to confirmed calendar event, every step is controlled, attributable, and visible to the right people."><div className="feature-grid feature-grid-large"><Feature n="01" title="Campaign objectives" text="Choose discovery calls, product demos, consultations, quote reviews, or specialist follow-ups from supported agent workflows."/><Feature n="02" title="Provider-aware capacity" text="Campaign concurrency automatically respects the lower of the subscription allowance and connected telephony account limits."/><Feature n="03" title="Outlook and Google scheduling" text="Read availability, create calendar events, and include meeting links without double-booking your team."/><Feature n="04" title="Team roles" text="Owners, admins, managers, members, and viewers receive only the controls their responsibilities require."/><Feature n="05" title="Prospect ledger" text="Every phone, email, SMS, and manual contact attempt stays attached to the prospect for a durable history."/><Feature n="06" title="Audit and compliance" text="Disclosure, opt-outs, launch attestations, provider events, and administrative changes are logged for review."/></div><div className="center-action"><a className="button button-primary" href={appPath}>Start free trial</a></div></PageFrame>; }

function PricingContent({ appPath }: { appPath: string }) { return <PageFrame eyebrow="PRICING" title="Straightforward platform pricing that leaves you in control." intro="Every plan includes the CRM, supported voice stacks, Outlook and Google scheduling, compliance controls, and permanent prospect outreach history. Higher tiers add capacity—not essential workflow paywalls."><div className="public-plan-grid">{plans.map((plan) => <article className={plan.best ? "featured" : ""} key={plan.name}>{plan.best ? <span className="plan-badge">MOST POPULAR</span> : null}<h2>{plan.name}</h2><strong>{plan.price}<small>/month</small></strong><p>{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><a className={`button ${plan.best ? "button-primary" : "button-secondary"}`} href={appPath}>Choose {plan.name}</a></article>)}</div><div className="pricing-note"><strong>14-day trial</strong><span>10 submitted calls · 1 campaign · 1 seat · 1 concurrent call · no credit card required</span></div><div className="pricing-note pricing-clarity"><strong>Provider costs stay transparent</strong><span>These are platform subscription fees. You connect your own telephony and AI accounts, and those providers bill their usage directly. A call counts only after the platform successfully submits it to the connected telephony provider.</span></div></PageFrame>; }

function SecurityContent() { return <PageFrame eyebrow="SECURITY & COMPLIANCE" title="Designed to make the safe path the normal path." intro="Security controls protect tenant data and provider credentials, while operational guardrails keep risky calls out of the dialer."><div className="security-grid"><Feature n="01" title="Tenant isolation" text="Every application query is scoped to the authenticated workspace, with server-side authorization for every write."/><Feature n="02" title="Encrypted integrations" text="Telephony and AI provider credentials are encrypted at rest and never returned to the browser after connection."/><Feature n="03" title="Role-based permissions" text="Sensitive team, billing, integration, audit, and platform actions require explicit server-validated permissions."/><Feature n="04" title="Signed provider callbacks" text="Twilio callback signatures are validated before call state or conversation actions are accepted."/><Feature n="05" title="Consent and DNC gates" text="Prospects without documented express consent and a current DNC check cannot enter the calling workflow."/><Feature n="06" title="Auditable administration" text="Workspace and platform-level changes create durable audit events with actor, time, target, and change details."/></div></PageFrame>; }

function ContactContent() { return <PageFrame eyebrow="CONTACT" title="Let’s talk about your calling workflow." intro="For product questions, enterprise account arrangements, security reviews, or support, contact our team."><div className="contact-card"><div><span className="eyebrow">GENERAL & SALES</span><h2>Start a conversation</h2><p>Tell us about your team, expected call volume, calendar provider, and the products or services you want the agent to represent.</p></div><a className="button button-primary" href="mailto:support@odinassetmanager.com?subject=AI%20Appointment%20Setter%20Inquiry">Email support@odinassetmanager.com</a></div></PageFrame>; }

function LegalContent({ title, kind }: { title: string; kind: "privacy" | "terms" }) { const privacy = kind === "privacy"; return <PageFrame eyebrow="LEGAL" title={title} intro={`Effective August 24, 2026. This ${privacy ? "policy" : "agreement"} describes the baseline terms for AI Appointment Setter.`}><article className="legal-content"><h2>{privacy ? "Information we process" : "Responsible use"}</h2><p>{privacy ? "We process account identity, workspace configuration, prospect data supplied by customers, call events, calendar data required to check availability and create appointments, and security/audit records." : "Customers must use the service only for lawful outreach, maintain required consent and DNC evidence, follow recording and caller-identification laws, and provide truthful product information."}</p><h2>{privacy ? "How information is used" : "Service and billing"}</h2><p>{privacy ? "Information is used to provide the service, secure accounts, execute authorized campaigns, schedule meetings, support customers, enforce limits, and maintain audit trails. Provider credentials are encrypted at rest." : "Plans impose stated feature and usage limits. Paid subscriptions may renew monthly until canceled. Platform administrators may issue documented complimentary or discounted access grants without changing standard public plan limits."}</p><h2>{privacy ? "Service providers and retention" : "AI and telephony"}</h2><p>{privacy ? "Connected telephony, AI, calendar, hosting, and billing providers process only the information required for their function. Retention varies by plan, legal obligations, and security needs." : "Calls use connected third-party telephony and AI providers. Customers are responsible for provider accounts, charges, configuration, and compliance. The AI must identify itself and must not impersonate a person."}</p><h2>Contact</h2><p>Questions may be sent to <a href="mailto:support@odinassetmanager.com">support@odinassetmanager.com</a>.</p></article></PageFrame>; }

function PageFrame({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) { return <section className="public-page"><div className="public-page-head"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div>{children}</section>; }
function Feature({ n, title, text }: { n: string; title: string; text: string }) { return <article className="public-feature"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>; }
